### ISSUE TITLE
github action for building and uploading pdf, epub to release when tag is pushed

### ISSUE THREAD

**Issue by thomasgeissl** [thomasgeissl/tamlab-latex-template#1]

**Comment by ben-wes** [comment]
i'm currently using this action:

```
name: Build PDF and Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install LaTeX
        run: sudo apt update && sudo apt install -y texlive texlive-latex-extra

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Project and Generate PDF
        run: npm run build

      - name: Rename PDF file
        run: mv thesis.pdf thesis_${{ github.ref_name }}.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: thesis_${{ github.ref_name }}.pdf
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
